# --- Entity IDs ---
tv = "remote.basement_tv"
tv_light = "light.tv_light"
speakers = "switch.speakers"
monitors = "switch.monitors"
desk_lights = "light.desk_lights"
ceiling_light = "light.ceiling_light"
laundry_light = "light.laundry_room_light"
stairs_light = "light.stairs_light"
closet_light = "light.closet_light"
curtain = "cover.left_curtain"